language: java
before_install:
  # download the latest android sdk and unzip
  - uname -a
  - pwd
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  - export ANDROID_HOME=~/build/ikhavkin/android-get/android-sdk-linux/
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - pwd
  - android list sdk
  - android list targets
  - android update sdk --filter 1,2,7 --no-ui --force
  - ls -al /home/travis/build/ikhavkin/android-get/android-sdk-linux/platform-tools/aapt
  - mvn clean test
